### PR TITLE
Optimized images #21

### PR DESCRIPTION
**Pull request by RichardLitt**

### CODE REVIEW

**Comment by RichardLitt** [comment]
Should work. Used gulp, clipped with photoshop, replaced css with rel paths.

**Comment by jedireza** [comment]
Nice thanks @RichardLitt. Just curious, what are these files used for?

```
image-src/bg_hr.png
image-src/blacktocat.png
image-src/icon_download.png
image-src/sprite_download.png
```

**Comment by RichardLitt** [comment]
No idea, they were in images before. 

—

**Comment by jedireza** [comment]
Ah. We should just get rid of those I think.

**Comment by RichardLitt** [comment]
Removed. Kept bg_hr as the relevant css is being used.

**Comment by jedireza** [comment]
:shipit: on a :ship: :sparkles: thanks!

**Comment by RichardLitt** [comment]
Cool. I don't have write access, someone else will have to accept.

**Comment by RichardLitt** [comment]
:palm_tree:

**Pull request merged**
