### PR TITLE
site design update

### PR DESCRIPTION
**Pull request by llkats**
I guess a PR is a good idea? See discussion in #7.

### CODE REVIEW

**Comment by RichardLitt** [comment]
:+1:

**Comment by llkats** [comment]
Gonna go ahead and merge. I'll be unable to update or give feedback on anything over the weekend as I'll be out of town until Sunday evening. Please feel free to update as you guys see fit. Thanks @RichardLitt and @jedireza for the help and feedback!

**Comment by jedireza** [comment]
Very cool. Thanks so much @llkats!! Have fun this weekend.

**Comment by RichardLitt** [comment]
Thanks @llkats!

**Comment by fmoliveira** [comment]
Congratulations @llkats , the job is awesome! I liked the mix of colours, they fit very well. :+1:

**Pull request merged**
