### PR TITLE
first pass at SF homepage

### PR DESCRIPTION
**Pull request by llkats**
This is a first pass at the Nodeschool SF homepage, forked from Nodeschool Campinas at the suggestion of @fmoliveira. Includes updated README with organizer information, basic homepage content with placeholder images, and a Code of Conduct file.

To run the site locally, clone the repository (if you have not yet done so) with the following command in the terminal:  
`git clone git@github.com:nodeschool/sanfrancisco.git`. 

Navigate to the new directory and run:

`npm install`
`npm start`

and visit the site at http://0.0.0.0:8080/

To push this live, I'll merge this branch into the `gh-pages` branch, but I just wanted to get some feedback first. I'm okay putting it online as-is, maybe with some copy saying the site is under construction. Also, please verify the organizer information in the README and the code-of-conduct file and let me know if you'd like the contact information changed.

Let me know if you have any questions! I'm hoping after this initial push to break out tasks so others can pitch in with content and stuffs. :raised_hands: :fireworks: :turtle:

### CODE REVIEW

**Comment by jedireza** [comment]
Looking good. A under-construction message is a good idea. I agree about an initial launch and breaking out tasks afterwards. I've confirmed my contact info is correct.

Thanks @llkats :sparkles::+1::sparkles:

**Comment by RichardLitt** [comment]
Looks good to me. Code of Conduct seems fine.

**Comment by fmoliveira** [comment]
Oh @llkats , please remember to change Google Analytics ID in "js/google.analytics.js". :+1:

**Comment by llkats** [comment]
Updated with under-construction text over the hero-image placeholder; removed Google Analytics id and just commented that JS file out of the index until the account is set up; updated anchor links to English.

**Comment by jedireza** [comment]
:shipit: on a :ship:

**Pull request merged**
