### PR TITLE
pull request for issue #82 added bootstap carousel, added caption-bg style for carousel caption 

### PR DESCRIPTION
**Pull request by goodbedford**
Hi,
This is a pull request for issue #82 
I added a bootstrap carousel and tried to keep the caption styling the same as before. I have the months July, June, and May committed out but are ready to add a img link. Also then some li tags will need to be added for carousel indictors. If you have other suggestions or questions let me know. In addition if you don't want to merge, give me some pointers on what to do different.
Thanks, see you at the august meet up.

### CODE REVIEW

**Comment by jedireza** [comment]
:boom: Thanks for submitting a PR! I should have some time in the next day or two to review if someone else doesn't jump in.

**Comment by llkats** [comment]
Hi! Thanks for making a pull request! Your markup looks very clean and well-formatted.

I believe one essential piece might be missing though: some JavaScript code to initialize the carousel! It looks like right now the page will still have a static stack of images at the bottom, one on top of the other. From what I understand, the hope for this feature is to have a dynamic rotation of images so we can consolidate space.

I believe this link will help: http://getbootstrap.com/javascript/#carouseloptions. Since it seems a minimal amount of JS to start the carousel, I think it'd be fine to include in inline `<script>` tags within the page. Please let us know here if you have any questions!

**Comment by goodbedford** [comment]
@llkats thanks for the feedback. I added an inline script to for each image to be 4seconds long and it is to initiate when the page loads.  Also I in regards to the stack of images at the bottom.  It only looks like that when you look at the index.html page in browser. But when you run Jekyll server you can see the pictures in a carousel and animated. It seems git pages runs Jekyll so you have to run in development to see the changes.  Please let me know if these corrections are pleasing.

**Comment by jedireza** [comment]
Looking good. I'm going to merge this to keep the ball rolling. Let's open another PR soon to get the other group photos added.

**Pull request merged**
