### PR TITLE
Webiste updates

### PR DESCRIPTION
**Pull request by jedireza**
1270018080-full

### CODE REVIEW

**Comment by jedireza** [comment]
The images are currently just pointing to flickr, if we think they're good, I can optimized them for the web and commit them to the repo.

**Comment by RichardLitt** [comment]
Works for me --- @llkats?

**Comment by llkats** [comment]
Beautiful!! Ship it good -- nice work, @jedireza!!!

**Comment by jedireza** [comment]
Cool. I'll ship as is so it's live. I'll create an issue for optimizing the images.

**Pull request merged**
