### PR TITLE
PST -> PDT

### PR DESCRIPTION
**Pull request by Trott**
We are now on Daylight Savings Time, not standard time. I guarantee this will be the most trivial pull request you deal with all day.

### CODE REVIEW

**Comment by jedireza** [comment]
I'm not sure about that. I'll need a timezone expert to review this.

**Comment by Trott** [comment]
Here's an easy way to check, assuming you are on Mac or Linux and have it set to non-Arizona Pacific Time: run `date` from the command line. Last week, it was saying PST. This week, it is saying PDT. 

You can also look at http://www.timeanddate.com/time/zone/usa/los-angeles where they have a chart showing that Los Angeles (and all of the West Coast of the U.S. excluding Arizona) are on PST from late October through early March, and then switch to PDT from early March until the late October.

**Comment by jedireza** [comment]
Haha. I was kidding.

**Comment by jedireza** [comment]
Thanks!

**Comment by Trott** [comment]
I was trolled. I need an Internet chaperone clearly.

**Pull request merged**
